name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: app
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U app -d app"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      APP_ENV: test
      DATABASE_URL: postgresql://app:app@postgres:5432/app?serverVersion=16&charset=utf8

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_pgsql, intl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Wait for Postgres to be healthy
        run: |
          for i in {1..30}; do
            (echo > /dev/tcp/127.0.0.1/5432) >/dev/null 2>&1 && echo "Postgres is up" && break
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Prepare test schema
        run: |
          php bin/console doctrine:database:create --if-not-exists --env=test
          # Jeśli masz migracje:
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
          # Lub alternatywnie bez migracji (jedna z metod, nie obie):
          # php bin/console doctrine:schema:create --env=test

      - name: Run tests
        run: vendor/bin/phpunit
