name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:16
        env:
          POSTGRES_DB: statki
          POSTGRES_USER: statki
          POSTGRES_PASSWORD: statki
        options: >-
          --health-cmd="pg_isready -U statki -d statki"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    env:
      APP_ENV: test
      DATABASE_URL: "postgresql://statki:statki@127.0.0.1:5432/statki?serverVersion=16&charset=utf8"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'
          extensions: pdo_pgsql, intl, mbstring, zip, dom, curl
          coverage: none

      - name: Validate Composer files
        run: composer validate --no-check-publish

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare .env
        run: |
          cp -n .env .env.backup || true
          cp -n .env.test .env || true

      - name: Wait for DB
        run: |
          for i in {1..30}; do
            if pg_isready -h 127.0.0.1 -p 5432 -U statki; then
              echo "DB is ready"; break;
            fi
            sleep 2
          done

      - name: Run migrations (test)
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run tests
        run: vendor/bin/phpunit
