name: Laravel CI

on:
    push:
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:16-alpine
                env:
                    POSTGRES_DB: statki
                    POSTGRES_USER: statki
                    POSTGRES_PASSWORD: statki
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd="pg_isready -U statki -d statki"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=10

        env:
            APP_ENV: test
            APP_KEY: base64:2H6…wstaw_swoj_klucz…
            APP_DEBUG: 0
            CACHE_DRIVER: array
            SESSION_DRIVER: array
            QUEUE_CONNECTION: sync
            DB_CONNECTION: pgsql
            DB_HOST: postgres
            DB_PORT: 5432
            DB_DATABASE: statki
            DB_USERNAME: statki
            DB_PASSWORD: statki

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: pdo_pgsql
                  coverage: none

            - name: Cache Composer dependencies
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: composer-

            - name: Install dependencies
              run: composer install --no-interaction --no-progress --prefer-dist

            - name: Generate application key
              run: php artisan key:generate --env=testing

            - name: Wait for Postgres to be healthy
              run: |
                  for i in {1..30}; do
                    pg_isready -h postgres -U statki -d statki && echo "Postgres is ready" && break
                    echo "Waiting for Postgres..."
                    sleep 2
                  done
                  sleep 3
              env:
                  PGPASSWORD: statki

            - name: Run migrations
              run: php artisan migrate --env=testing --force

            - name: Run tests
              run: php artisan test --env=testing
