name: CI

on:
    push:
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:16-alpine
                env:
                    POSTGRES_DB: app
                    POSTGRES_USER: app
                    POSTGRES_PASSWORD: app
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd="pg_isready -U app -d app"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=10

        env:
            APP_ENV: test
            APP_DEBUG: 0
            DATABASE_URL: postgresql://app:app@postgres:5432/app?serverVersion=16&charset=utf8

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: pdo_pgsql
                  coverage: none

            - name: Install Composer dependencies
              run: composer install --no-interaction --no-progress --prefer-dist

            # zamiast getent — używamy pg_isready
            - name: Wait for Postgres to be healthy
              run: |
                  echo "DATABASE_URL=$DATABASE_URL"
                  for i in {1..30}; do
                    pg_isready -h postgres -U app -d app && echo "Postgres is ready" && break
                    echo "Waiting for Postgres..."
                    sleep 2
                  done

            - name: Prepare test schema
              run: |
                  php bin/console doctrine:database:create --if-not-exists --env=test
                  php bin/console doctrine:migrations:migrate --no-interaction --env=test
                  # albo alternatywnie, jeśli brak migracji:
                  # php bin/console doctrine:schema:create --env=test

            - name: Run tests
              run: vendor/bin/phpunit
